# Generated by Django 6.0.2 on 2026-03-06 06:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название группы')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год набора')),
                ('students', models.TextField(blank=True, verbose_name='Студенты (по одной строке)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название программы')),
                ('class_level', models.CharField(choices=[('1', '1 класс'), ('2', '2 класс'), ('3', '3 класс'), ('4', '4 класс'), ('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], max_length=10, verbose_name='Класс')),
                ('year', models.IntegerField(verbose_name='Учебный год')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculums', to='teacher.studentgroup', verbose_name='Группа студентов')),
            ],
            options={
                'verbose_name': 'Рабочая программа',
                'verbose_name_plural': 'Рабочие программы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='teacher.studentgroup', verbose_name='Группа')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='teacher.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='NeuralNetworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('model_file', models.FileField(upload_to='nn_models/%Y/%m/%d/', verbose_name='Файл модели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='Точность (MAE)')),
                ('training_samples', models.IntegerField(default=0, verbose_name='Количество примеров обучения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_trained', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обучение')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nn_models', to='teacher.curriculum', verbose_name='Рабочая программа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nn_models', to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nn_models', to='teacher.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Нейросетевая модель',
                'verbose_name_plural': 'Нейросетевые модели',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('date', models.DateField(verbose_name='Дата урока')),
                ('objectives', models.TextField(blank=True, verbose_name='Цели и задачи')),
                ('materials', models.TextField(blank=True, verbose_name='Материалы и ресурсы')),
                ('content', models.TextField(blank=True, verbose_name='Содержание урока')),
                ('homework', models.TextField(blank=True, verbose_name='Домашнее задание')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teacher.curriculum', verbose_name='Рабочая программа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='teacher.studentgroup', verbose_name='Группа')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='teacher.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GradePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='ФИО студента')),
                ('predicted_grade', models.FloatField(verbose_name='Предсказанная оценка')),
                ('confidence', models.FloatField(verbose_name='Уверенность (%)')),
                ('average_grade', models.FloatField(verbose_name='Средняя оценка студента')),
                ('attendance', models.FloatField(verbose_name='Посещаемость (%)')),
                ('test_average', models.FloatField(verbose_name='Средний балл теста')),
                ('homework_completion', models.FloatField(verbose_name='Выполнение ДЗ (%)')),
                ('prediction_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата предсказания')),
                ('actual_grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Фактическая оценка')),
                ('is_accurate', models.BooleanField(blank=True, null=True, verbose_name='Точное предсказание')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='teacher.curriculum', verbose_name='Рабочая программа')),
                ('nn_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='teacher.neuralnetworkmodel', verbose_name='Нейросетевая модель')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='teacher.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предсказание оценки',
                'verbose_name_plural': 'Предсказания оценок',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='ФИО студента')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата оценки')),
                ('grade_type', models.CharField(choices=[('homework', 'Домашнее задание'), ('classwork', 'Классная работа'), ('test', 'Контрольная работа'), ('exam', 'Экзамен'), ('other', 'Прочее')], default='classwork', max_length=50, verbose_name='Тип работы')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='teacher.curriculum', verbose_name='Рабочая программа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='teacher.lesson', verbose_name='Урок')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='teacher.studentgroup', verbose_name='Группа')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='teacher.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-date', 'student_name'],
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculums', to='teacher.subject', verbose_name='Предмет'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('test_type', models.CharField(choices=[('test', 'Тест'), ('control_work', 'Контрольная работа'), ('quiz', 'Викторина'), ('exam', 'Экзамен'), ('survey', 'Опрос')], default='test', max_length=50, verbose_name='Тип проверки')),
                ('content', models.TextField(verbose_name='Содержание (вопросы/задания)')),
                ('answer_key', models.TextField(blank=True, verbose_name='Ключ ответов')),
                ('max_score', models.IntegerField(default=100, verbose_name='Максимальный балл')),
                ('duration_minutes', models.IntegerField(default=45, verbose_name='Продолжительность (минут)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='teacher.studentgroup', verbose_name='Группа')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='teacher.curriculum', verbose_name='Рабочая программа')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='teacher.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Тест/Контрольная работа',
                'verbose_name_plural': 'Тесты/Контрольные работы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='ФИО ученика')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Набранный балл')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Процент выполнения')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('date_completed', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='teacher.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-date_completed'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('hours', models.IntegerField(default=1, verbose_name='Количество часов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='teacher.curriculum', verbose_name='Рабочая программа')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['curriculum', 'order'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='teacher.topic', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='teacher.topic', verbose_name='Тема'),
        ),
    ]
