# Generated by Django 6.0.2 on 2026-03-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название викторины')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=20, verbose_name='Уровень сложности')),
                ('time_limit', models.IntegerField(default=15, help_text='0 - без ограничения', verbose_name='Ограничение времени (минуты)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='teacher.studentgroup', verbose_name='Группа')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='teacher.curriculum', verbose_name='Рабочая программа')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='teacher.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='teacher.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Викторина',
                'verbose_name_plural': 'Викторины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='ФИО студента')),
                ('answers', models.JSONField(help_text='Словарь: question_id -> ответ', verbose_name='Ответы')),
                ('score', models.IntegerField(default=0, verbose_name='Набранные баллы')),
                ('max_score', models.IntegerField(default=0, verbose_name='Максимальные баллы')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Процент выполнения')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Время выполнения (секунды)')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='teacher.studentgroup', verbose_name='Группа')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='teacher.quiz', verbose_name='Викторина')),
            ],
            options={
                'verbose_name': 'Попытка викторины',
                'verbose_name_plural': 'Попытки викторин',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('single_choice', 'Один правильный ответ'), ('multiple_choice', 'Несколько правильных ответов'), ('true_false', 'Верно/Неверно'), ('short_answer', 'Короткий ответ'), ('essay', 'Эссе')], default='single_choice', max_length=20, verbose_name='Тип вопроса')),
                ('options', models.JSONField(blank=True, help_text='Для вопросов с вариантами: список строк', null=True, verbose_name='Варианты ответов')),
                ('correct_answer', models.JSONField(help_text='Для single_choice: индекс правильного ответа, для multiple_choice: список индексов, для true_false: true/false, для других: текст ответа', verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, help_text='Объяснение правильного ответа', verbose_name='Пояснение')),
                ('points', models.IntegerField(default=1, verbose_name='Баллы за вопрос')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacher.quiz', verbose_name='Викторина')),
            ],
            options={
                'verbose_name': 'Вопрос викторины',
                'verbose_name_plural': 'Вопросы викторины',
                'ordering': ['quiz', 'order'],
            },
        ),
    ]
